# Site settings
title: SwapAVote - Organizing Apathy
email:
description: I won't vote if you won't vote.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "SwapAVote.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
